### ISSUE TITLE
Menu doesn't "always" open in single click

### ISSUE THREAD

**Issue by bobdesaunois** [CompraBV/onepage#11]
You have to click twice on the menu in the editor before it actually opens.

**Comment by NathanBastiaans** [comment]
Fixed - Problem occurred when not properly closing the sidebar (not clicking the menu button (Which nobody actually does by the way) ). The problem was when it did not properly close someone (probably me) wrote $(this).(stupidjqueryfunctions); which should have been $('#sidebar-button').(stupidjqueryfunctions).
